version: "3.9"
services:
  db:
    image: supabase/postgres:15.1.1.51
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/rag
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8000:8000"
volumes:
  pgdata:
